### ISSUE TITLE
enter and left promiscuous mode...

### ISSUE THREAD

**Issue by gazambuja** [br101/horst#13]
Hi, Im running horst every few minutes, to capture some data over a Router with openwrt.
My router have some stations connected via wifi, and (almost) every time horst is killed, the stations are disconected.

Im using this command to run horst (run horst, save content, kill after 55 seconds):
(horst -i mon0 -t 60 -f NULL -f QDATA -f PROBE -f ASSOC -o /tmp/capture.csv -q ) & sleep 55 ; kill $!;

and in logread I have this:

	Fri May 29 20:23:21 2015 kern.info kernel: [ 2521.470000] device mon0 entered promiscuous mode
	Fri May 29 20:24:00 2015 daemon.info hostapd: wlan1-1: STA 2c:8a:73:A4:13:15 IEEE 802.11: authenticated
	Fri May 29 20:24:00 2015 daemon.info hostapd: wlan1-1: STA 2c:8a:73:A4:13:15 IEEE 802.11: associated (aid 1)
	Fri May 29 20:24:00 2015 daemon.info hostapd: wlan1-1: STA 2c:8a:73:A4:13:15 WPA: pairwise key handshake completed (RSN)
	Fri May 29 20:24:16 2015 kern.info kernel: [ 2576.480000] device mon0 left promiscuous mode
	Fri May 29 20:24:54 2015 daemon.info hostapd: wlan0-1: STA 2c:8a:73:A4:13:15 IEEE 802.11: disassociated due to inactivity
	Fri May 29 20:24:55 2015 daemon.info hostapd: wlan0-1: STA 2c:8a:73:A4:13:15 IEEE 802.11: deauthenticated due to inactivity (timer DEAUTH/REMOVE)

How I can prevent the horst left promiscuous mode?

**Comment by br101** [comment]
Hi! That's strange and "shouldn't happen"... Setting promiscuous mode on the monitor interface should not interfere with the hostapd process... Which driver do you use?

**Comment by br101** [comment]
But to work around this issue, you could maybe try to keep horst running and use the -X and -x options to start and pause capturing...

**Comment by gazambuja** [comment]
Im using mac80211.
I will research about -X option.
I have two ssid in this router, if I remove one, hostapd and horst work fine.

**Comment by br101** [comment]
OK, maybe an issue with multiple vif (AP Interfaces)... but most likely a driver bug. I will check to verify, but please tell me your *driver* (ath9k, rtl8192cu, ...???) and wifi chipset (Atheros, Broadcom, Ralink,... ???)

**Comment by gazambuja** [comment]
Im using a TL-WDR3500 with:
*Atheros AR9340 2.4GHz 802.11bgn*

More info: http://wiki.openwrt.org/toh/tp-link/tl-wdr3500



Gustavo Azambuja
http://gazambuja.com
<http://gazambuja.com>
Uruguay:     *091 300 333* (Montevideo - Mobile)

**Comment by br101** [comment]
Ok, good, I have a WDR3600 - so basically the same hardware. I tried to follow your scenario and also set up two AP interfaces with psk2. I connected one device to the second AP interface (wlan0-1) and started horst, just like you - but the client kept connected after horst was killed and the interface left promiscuous mode.  Also I looked at the log you posted above: the client gets disassociated more than 30 seconds after horst got killed, so I doubt that there is a direct connection between the two... In any case you'd need to provide me with more detailed instructions on how to reproduce this problem... or I'll close this issue.

**Comment by br101** [comment]
Oh BTW, if you think this is related to the promiscuous mode, you can just set the interface into promisc mode without horst by "ifconfig mon0 promisc" and unset it with "ifconfig mon0 -promisc". Also you should see the same effect by running tcpdump on mon0...

**Comment by gazambuja** [comment]
Ok Bruno, I will make more test and test with your suggest this week. If I
sure about horst and problem I will reopen the case.

Thanks

Gustavo Azambuja
http://gazambuja.com
<http://gazambuja.com>
Uruguay:     *091 300 333* (Montevideo - Mobile)
