### ISSUE TITLE
Better error handling

### ISSUE THREAD

**Issue by Skrupellos** [br101/horst#17]
Based in 33f6562096c6b05153fe42fdeea79d49777e6bd4

Provoking an error, by starting horst on an interface which is down, results in the following output:
```
Set 'interface' = 'wlp2s0'
Can't activate pcap: -9
horst: Couldn't open packet socket: Success
```

This could be done better :)
  * Use `pcap_perror()` or similar to get a meaningful PCAP error message.
  * Stop horst after the first error (There shouldn't be any further error messages). Forgot to check a return value?
  * The classical "Error: Success" in the last line also indicates an inpropper return value or `errno` handling.

(Perhaps I find time to fix this by my self, but not in the near feature)

**Comment by tuomasjjrasanen** [comment]
I agree, the error handling scheme should be improved. Currently there are lots of void functions, lots of errors are silently ignored, and so on. So, lots of contributions are needed.

**Comment by br101** [comment]
Well, error handling can always be better... Right now the error in the case of a nonexistent interface is:

```
sudo ./horst -i wlan1x
Set 'mac_names'
Set 'interface' = 'wlan1x'
Could not open mac name file '/tmp/dhcp.leases'
interface wlan1x does not exist
interface wlan1x does not exist
interface wlan1x does not exist
horst: failed to add virtual monitor interface: No such device
horst: Could not get flags for wlan1x: No such device
```

or in the case of compiling with PCAP=1 WEXT=1 , which is not recommended:

```
sudo ./horst -i wlan1x
Set 'mac_names'
Set 'interface' = 'wlan1x'
Could not open mac name file '/tmp/dhcp.leases'
horst: Could not get flags for wlan1x: No such device
horst: failed to bring interface 'wlan1x' up: No such device
horst: Could not get flags for wlan1x: No such device
```

As I think this is OK and in general error handling can be improved in 99% of all programs I will close this issue.
