### ISSUE TITLE
Feature Request: Bring interfaces up

### ISSUE THREAD

**Issue by Skrupellos** [br101/horst#18]
`horst.sh` brings Interfaces up before using them. `horst` should also be able to do so, in order to fully replace `horst.sh` after #14 has been implemented.

**Comment by tuomasjjrasanen** [comment]
Hmmh.. in my setup, I do not have to bring up the interface explicitly, I wonder why? Any ideas? Could it be that only madwifi drivers requires it?

**Comment by Skrupellos** [comment]
Ok, I should have been more verbose. Its an iwlwifi card (Wireless 7260).

```
$ systemctl stop NetworkManager.service
$ systemctl stop NetworkManager-dispatcher.service
$ ip link
4: wlp2s0: <BROADCAST,MULTICAST> mtu 1500 qdisc mq state DOWN mode DEFAULT group default qlen 1000
$ rfkill list
2: phy0: Wireless LAN
	Soft blocked: no
	Hard blocked: no
$ horst -i wlp2s0
Set 'interface' = 'wlp2s0'
Can't activate pcap: -9
horst: Couldn't open packet socket: Success
$ ip link set up wlp2s0
$ horst -i wlp2s0
... works
```

**Comment by tuomasjjrasanen** [comment]
Can you test this branch, please: https://github.com/tuomasjjrasanen/horst/tree/bring_interface_up

**Comment by br101** [comment]
Also you use horst with the PCAP option, which is disabled by default. Any reason you do so?

**Comment by Skrupellos** [comment]
@tuomasjjrasanen: Now I get the following output (with and without PCAP=1)
```
Set 'interface' = 'wlp2s0'
failed to send a netlink message: Object busy
horst: failed to set interface 'wlp2s0' to monitor mode
horst: interface 'wlp2s0' is not in monitor mode, adding a virtual monitor interface
```

@br101: Not in particular. I thought it would bring some extra features :)

**Comment by tuomasjjrasanen** [comment]
That looks good to me now, it tells that something is using your wlp2s0 interface and it cannot be modified because its busy, horst then falls back to creating a extra monitor interface and uses that instead.

**Comment by tuomasjjrasanen** [comment]
@br101 So I think the bring_interface_up branch fixes the issue, I'll make a pull request.

**Comment by Skrupellos** [comment]
@tuomasjjrasanen you are probably right (even though I didn't spot any suspicious process using the WiFi). Some reboots later it worked. I will test this further in the next days. But I think we can consider this bug as fixed.

**Comment by br101** [comment]
The PCAP option does not bring you any benefit, and I do not recommend to use it, which is why its off by default. It is there mostly for compatibility reasons with BSD systems.
