### ISSUE TITLE
Packet type filter leaks packets with unknown/unmapped types

### ISSUE THREAD

**Issue by tuomasjjrasanen** [br101/horst#30]
## The problem

If `horst` is configured to filter out all but `BEACON` packets (`-f BEACON`), also `ACTION` packets get printed. This is because `ACTION` frames are not mapped to any packet type and because all non-mapped types are always included.

Adding a packet type filter always adds the generic frame type filter too (https://github.com/br101/horst/blob/master/conf_options.c#L251) and all packets belonging to generic group are always included (https://github.com/br101/horst/blob/master/main.c#L257) in the results.

So in other words, in this case, all packets with `pkt_types == PKT_TYPE_MGMT` get included in the results because `-f BEACON` not only adds PKT_TYPE_BEACON to the filter but also PKT_TYPE_MGMT. This rule matches all action frames because they are not mapped to any packet types, they only belong to the generic management frame group.

## Expected behavior

If `horst` is configured to use inclusive packet type filtering it should filter out all except packets matching the given packet types.

In my opinion, the current behavior is wrong: unmapped frames should not get included in the result set, the filter is inclusive by definition so all non-matching packets should be excluded.

## Conclusions

This specific problem could be fixed by adding `PKT_TYPE_ACTION` and mapping all action frames to it, but I think the problem is more generic and it should be fixed by filtering out (in `filter_packet()`) all packets which do not have any subtype flags set. Opinions?

**Comment by br101** [comment]
Agreed. Another option would be to get rid of PKT_TYPE_<subtype> (which is just a selection of "interesting" type) and use the full types of the WLAN header (as in wlan80211.h), but then we include a lot of things which are usually not interesting...

**Comment by tuomasjjrasanen** [comment]
We cannot get rid of PKT_TYPE easily because packet type filtering covers also higher level protocols. So I fixed the issue by excluding all unmapped frames from the results if any packet type filter rule was given: https://github.com/br101/horst/pull/33

However, I think supporting the full range of 802.11 frame type filters would be really cool, it would probably just mean that there would be a separate frame type filter and then the packet type filter would be left to higher level protocols.

**Comment by br101** [comment]
Implemented full 802.11 type/subtype filtering. Please check.

**Comment by tuomasjjrasanen** [comment]
Looks good and seems to work well. The "filter window problem" could be fixed by moving some filter groups to sub-windows, for example management, control and data frame filters, and pressing 'm', 'c' or 'd' would open corresponding frame filter windows. The top-level checkbox would still indicate the state of the frame type bit, but in order to see/modify sub-type bits, one would need to open one of the sub-windows.. what do you think?

**Comment by br101** [comment]
I prefer only one window for filters... I have now defined unique chars for each frame type/subtype and the other filters and I think it works out well enough. We also use these chars in the history window to identify the frames, so that way they are consistent and they are a kind of short ID of the subtype. 

Otherwise I'd prefer to add mouse support or navigation by arrow keys to simplify the filter window navigation.
