### ISSUE TITLE
OSX: Build issues

### ISSUE THREAD

**Issue by JiantaoFu** [br101/horst#34]
JIANFU-M-M0AH:horst jeromy$ make PCAP=1
echo '-Wall -Wextra -g -I. -DDO_DEBUG -DPCAP' | cmp -s - .buildflags || echo '-Wall -Wextra -g -I. -DDO_DEBUG -DPCAP' > .buildflags
cc -Wall -Wextra -g -I. -DDO_DEBUG -DPCAP   -c -o average.o average.c
cc -Wall -Wextra -g -I. -DDO_DEBUG -DPCAP   -c -o capture-pcap.o capture-pcap.c
cc -Wall -Wextra -g -I. -DDO_DEBUG -DPCAP   -c -o channel.o channel.c
cc -Wall -Wextra -g -I. -DDO_DEBUG -DPCAP   -c -o conf_options.o conf_options.c
cc -Wall -Wextra -g -I. -DDO_DEBUG -DPCAP   -c -o control.o control.c
cc -Wall -Wextra -g -I. -DDO_DEBUG -DPCAP   -c -o display-channel.o display-channel.c
cc -Wall -Wextra -g -I. -DDO_DEBUG -DPCAP   -c -o display-essid.o display-essid.c
cc -Wall -Wextra -g -I. -DDO_DEBUG -DPCAP   -c -o display-filter.o display-filter.c
cc -Wall -Wextra -g -I. -DDO_DEBUG -DPCAP   -c -o display-help.o display-help.c
cc -Wall -Wextra -g -I. -DDO_DEBUG -DPCAP   -c -o display-history.o display-history.c
cc -Wall -Wextra -g -I. -DDO_DEBUG -DPCAP   -c -o display-main.o display-main.c
cc -Wall -Wextra -g -I. -DDO_DEBUG -DPCAP   -c -o display-spectrum.o display-spectrum.c
cc -Wall -Wextra -g -I. -DDO_DEBUG -DPCAP   -c -o display-statistics.o display-statistics.c
cc -Wall -Wextra -g -I. -DDO_DEBUG -DPCAP   -c -o display.o display.c
cc -Wall -Wextra -g -I. -DDO_DEBUG -DPCAP   -c -o essid.o essid.c
cc -Wall -Wextra -g -I. -DDO_DEBUG -DPCAP   -c -o ieee80211_util.o ieee80211_util.c
Package libnl-3.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `libnl-3.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libnl-3.0' found
cc -c -Wall -Wextra -g -I. -DDO_DEBUG -DPCAP  -o ifctrl-nl80211.o .buildflags
clang: warning: .buildflags: 'linker' input unused
clang: warning: argument unused during compilation: '-Wall'
clang: warning: argument unused during compilation: '-Wextra'
clang: warning: argument unused during compilation: '-g'
clang: warning: argument unused during compilation: '-I .'
clang: warning: argument unused during compilation: '-D DO_DEBUG'
clang: warning: argument unused during compilation: '-D PCAP'
cc -Wall -Wextra -g -I. -DDO_DEBUG -DPCAP   -c -o listsort.o listsort.c
cc -Wall -Wextra -g -I. -DDO_DEBUG -DPCAP   -c -o main.o main.c
In file included from main.c:32:
In file included from ./main.h:26:
./ccan/list/list.h:129:9: warning: 'LIST_HEAD' macro redefined [-Wmacro-redefined]
#define LIST_HEAD(name) \
        ^
/usr/include/sys/queue.h:417:9: note: previous definition is here
#define LIST_HEAD(name, type)                                           \
        ^
main.c:230:52: warning: format specifies type 'long' but the argument has type '__darwin_suseconds_t'
      (aka 'int') [-Wformat]
        i += snprintf(buf + i, sizeof(buf) - i, ".%06ld", the_time.tv_usec);
                                                  ~~~~~   ^~~~~~~~~~~~~~~~
                                                  %06d
/usr/include/secure/_stdio.h:57:62: note: expanded from macro 'snprintf'
  __builtin___snprintf_chk (str, len, 0, __darwin_obsz(str), __VA_ARGS__)
                                                             ^
2 warnings generated.
cc -Wall -Wextra -g -I. -DDO_DEBUG -DPCAP   -c -o network.o network.c
cc -Wall -Wextra -g -I. -DDO_DEBUG -DPCAP   -c -o node.o node.c
cc -Wall -Wextra -g -I. -DDO_DEBUG -DPCAP   -c -o protocol_parser.o protocol_parser.c
cc -Wall -Wextra -g -I. -DDO_DEBUG -DPCAP   -c -o protocol_parser_wlan.o protocol_parser_wlan.c
cc -Wall -Wextra -g -I. -DDO_DEBUG -DPCAP   -c -o radiotap/radiotap.o radiotap/radiotap.c
cc -Wall -Wextra -g -I. -DDO_DEBUG -DPCAP   -c -o util.o util.c
cc -Wall -Wextra -g -I. -DDO_DEBUG -DPCAP   -c -o wext.o wext.c
cc -Wall -Wextra -g -I. -DDO_DEBUG -DPCAP   -c -o wlan_util.o wlan_util.c
cc  -o horst average.o capture-pcap.o channel.o conf_options.o control.o display-channel.o display-essid.o display-filter.o display-help.o display-history.o display-main.o display-spectrum.o display-statistics.o display.o essid.o ieee80211_util.o ifctrl-nl80211.o listsort.o main.o network.o node.o protocol_parser.o protocol_parser_wlan.o radiotap/radiotap.o util.o wext.o wlan_util.o -lncurses -lm -lpcap -lnl-3 -lnl-genl-3
clang: error: no such file or directory: 'ifctrl-nl80211.o'
make: *** [horst] Error 1

**Comment by br101** [comment]
You can't use ifctrl-nl80211.o on OSX. You'd need to adapt your makefile (completely remove -lnl-3 and -lnl-genl03) and make some dummy functions for the functions in that file. Sorry OSX is poorly supported...

**Comment by br101** [comment]
Could you try with the latest version and `make PCAP=1 WEXT=0 LIBNL=0`?

BTW: We need a capable OSX developer which can implement setting monitor mode, setting channels, etc... for OSX...

**Comment by JiantaoFu** [comment]
JIANFU-M-M0AH:horst jeromy$ make PCAP=1 WEXT=0 LIBNL=0  
gcc -MM average.c capture-pcap.c channel.c conf_options.c control.c display-channel.c display-essid.c display-filter.c display-help.c display-history.c display-main.c display-spectrum.c display-statistics.c display.c essid.c ieee80211_util.c ifctrl-ioctl.c listsort.c main.c network.c node.c protocol_parser.c protocol_parser_wlan.c radiotap/radiotap.c util.c wlan_util.c ifctrl-nl80211.c >.objdeps.mk
In file included from channel.c:22:
In file included from ./main.h:26:
./ccan/list/list.h:7:10: fatal error: 'ccan/str/str.h' file not found
#include <ccan/str/str.h>
         ^
1 error generated.
In file included from conf_options.c:25:
In file included from ./main.h:26:
./ccan/list/list.h:7:10: fatal error: 'ccan/str/str.h' file not found
#include <ccan/str/str.h>
         ^
1 error generated.
In file included from control.c:27:
In file included from ./main.h:26:
./ccan/list/list.h:7:10: fatal error: 'ccan/str/str.h' file not found
#include <ccan/str/str.h>
         ^
1 error generated.
In file included from display-channel.c:25:
In file included from ./main.h:26:
./ccan/list/list.h:7:10: fatal error: 'ccan/str/str.h' file not found
#include <ccan/str/str.h>
         ^
1 error generated.
In file included from display-essid.c:25:
In file included from ./main.h:26:
./ccan/list/list.h:7:10: fatal error: 'ccan/str/str.h' file not found
#include <ccan/str/str.h>
         ^
1 error generated.
In file included from display-filter.c:25:
In file included from ./main.h:26:
./ccan/list/list.h:7:10: fatal error: 'ccan/str/str.h' file not found
#include <ccan/str/str.h>
         ^
1 error generated.
In file included from display-help.c:25:
In file included from ./main.h:26:
./ccan/list/list.h:7:10: fatal error: 'ccan/str/str.h' file not found
#include <ccan/str/str.h>
         ^
1 error generated.
In file included from display-history.c:25:
In file included from ./main.h:26:
./ccan/list/list.h:7:10: fatal error: 'ccan/str/str.h' file not found
#include <ccan/str/str.h>
         ^
1 error generated.
In file included from display-main.c:26:
In file included from ./main.h:26:
./ccan/list/list.h:7:10: fatal error: 'ccan/str/str.h' file not found
#include <ccan/str/str.h>
         ^
1 error generated.
In file included from display-spectrum.c:25:
In file included from ./main.h:26:
./ccan/list/list.h:7:10: fatal error: 'ccan/str/str.h' file not found
#include <ccan/str/str.h>
         ^
1 error generated.
In file included from display-statistics.c:25:
In file included from ./main.h:26:
./ccan/list/list.h:7:10: fatal error: 'ccan/str/str.h' file not found
#include <ccan/str/str.h>
         ^
1 error generated.
In file included from display.c:31:
In file included from ./main.h:26:
./ccan/list/list.h:7:10: fatal error: 'ccan/str/str.h' file not found
#include <ccan/str/str.h>
         ^
1 error generated.
In file included from essid.c:23:
In file included from ./main.h:26:
./ccan/list/list.h:7:10: fatal error: 'ccan/str/str.h' file not found
#include <ccan/str/str.h>
         ^
1 error generated.
In file included from ieee80211_util.c:23:
In file included from ./main.h:26:
./ccan/list/list.h:7:10: fatal error: 'ccan/str/str.h' file not found
#include <ccan/str/str.h>
         ^
1 error generated.
In file included from listsort.c:46:
./ccan/list/list.h:7:10: fatal error: 'ccan/str/str.h' file not found
#include <ccan/str/str.h>
         ^
1 error generated.
In file included from main.c:32:
In file included from ./main.h:26:
./ccan/list/list.h:7:10: fatal error: 'ccan/str/str.h' file not found
#include <ccan/str/str.h>
         ^
1 error generated.
In file included from network.c:30:
In file included from ./main.h:26:
./ccan/list/list.h:7:10: fatal error: 'ccan/str/str.h' file not found
#include <ccan/str/str.h>
         ^
1 error generated.
In file included from node.c:24:
In file included from ./main.h:26:
./ccan/list/list.h:7:10: fatal error: 'ccan/str/str.h' file not found
#include <ccan/str/str.h>
         ^
1 error generated.
In file included from protocol_parser.c:31:
In file included from ./main.h:26:
./ccan/list/list.h:7:10: fatal error: 'ccan/str/str.h' file not found
#include <ccan/str/str.h>
         ^
1 error generated.
In file included from protocol_parser_wlan.c:30:
In file included from ./main.h:26:
./ccan/list/list.h:7:10: fatal error: 'ccan/str/str.h' file not found
#include <ccan/str/str.h>
         ^
1 error generated.
In file included from wlan_util.c:20:
In file included from ./main.h:26:
./ccan/list/list.h:7:10: fatal error: 'ccan/str/str.h' file not found
#include <ccan/str/str.h>
         ^
1 error generated.
ifctrl-nl80211.c:29:10: fatal error: 'netlink/attr.h' file not found
#include <netlink/attr.h>
         ^
1 error generated.
echo '-Wall -Wextra -g -I. -DDO_DEBUG -DPCAP' | cmp -s - .buildflags || echo '-Wall -Wextra -g -I. -DDO_DEBUG -DPCAP' > .buildflags
cc -Wall -Wextra -g -I. -DDO_DEBUG -DPCAP   -c -o average.o average.c
cc -Wall -Wextra -g -I. -DDO_DEBUG -DPCAP   -c -o capture-pcap.o capture-pcap.c
cc -Wall -Wextra -g -I. -DDO_DEBUG -DPCAP   -c -o channel.o channel.c
cc -Wall -Wextra -g -I. -DDO_DEBUG -DPCAP   -c -o conf_options.o conf_options.c
cc -Wall -Wextra -g -I. -DDO_DEBUG -DPCAP   -c -o control.o control.c
cc -Wall -Wextra -g -I. -DDO_DEBUG -DPCAP   -c -o display-channel.o display-channel.c
cc -Wall -Wextra -g -I. -DDO_DEBUG -DPCAP   -c -o display-essid.o display-essid.c
cc -Wall -Wextra -g -I. -DDO_DEBUG -DPCAP   -c -o display-filter.o display-filter.c
cc -Wall -Wextra -g -I. -DDO_DEBUG -DPCAP   -c -o display-help.o display-help.c
cc -Wall -Wextra -g -I. -DDO_DEBUG -DPCAP   -c -o display-history.o display-history.c
cc -Wall -Wextra -g -I. -DDO_DEBUG -DPCAP   -c -o display-main.o display-main.c
cc -Wall -Wextra -g -I. -DDO_DEBUG -DPCAP   -c -o display-spectrum.o display-spectrum.c
cc -Wall -Wextra -g -I. -DDO_DEBUG -DPCAP   -c -o display-statistics.o display-statistics.c
cc -Wall -Wextra -g -I. -DDO_DEBUG -DPCAP   -c -o display.o display.c
cc -Wall -Wextra -g -I. -DDO_DEBUG -DPCAP   -c -o essid.o essid.c
cc -Wall -Wextra -g -I. -DDO_DEBUG -DPCAP   -c -o ieee80211_util.o ieee80211_util.c
cc -Wall -Wextra -g -I. -DDO_DEBUG -DPCAP   -c -o ifctrl-ioctl.o ifctrl-ioctl.c
cc -Wall -Wextra -g -I. -DDO_DEBUG -DPCAP   -c -o listsort.o listsort.c
cc -Wall -Wextra -g -I. -DDO_DEBUG -DPCAP   -c -o main.o main.c
In file included from main.c:32:
In file included from ./main.h:26:
./ccan/list/list.h:129:9: warning: 'LIST_HEAD' macro redefined [-Wmacro-redefined]
#define LIST_HEAD(name) \
        ^
/usr/include/sys/queue.h:417:9: note: previous definition is here
#define LIST_HEAD(name, type)                                           \
        ^
main.c:230:52: warning: format specifies type 'long' but the argument has type '__darwin_suseconds_t' (aka 'int') [-Wformat]
        i += snprintf(buf + i, sizeof(buf) - i, ".%06ld", the_time.tv_usec);
                                                  ~~~~~   ^~~~~~~~~~~~~~~~
                                                  %06d
/usr/include/secure/_stdio.h:57:62: note: expanded from macro 'snprintf'
  __builtin___snprintf_chk (str, len, 0, __darwin_obsz(str), __VA_ARGS__)
                                                             ^
2 warnings generated.
cc -Wall -Wextra -g -I. -DDO_DEBUG -DPCAP   -c -o network.o network.c
cc -Wall -Wextra -g -I. -DDO_DEBUG -DPCAP   -c -o node.o node.c
cc -Wall -Wextra -g -I. -DDO_DEBUG -DPCAP   -c -o protocol_parser.o protocol_parser.c
cc -Wall -Wextra -g -I. -DDO_DEBUG -DPCAP   -c -o protocol_parser_wlan.o protocol_parser_wlan.c
cc -Wall -Wextra -g -I. -DDO_DEBUG -DPCAP   -c -o radiotap/radiotap.o radiotap/radiotap.c
cc -Wall -Wextra -g -I. -DDO_DEBUG -DPCAP   -c -o util.o util.c
cc -Wall -Wextra -g -I. -DDO_DEBUG -DPCAP   -c -o wlan_util.o wlan_util.c
Package libnl-3.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `libnl-3.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libnl-3.0' found
cc -c -Wall -Wextra -g -I. -DDO_DEBUG -DPCAP  -o ifctrl-nl80211.o .buildflags
clang: warning: .buildflags: 'linker' input unused
clang: warning: argument unused during compilation: '-Wall'
clang: warning: argument unused during compilation: '-Wextra'
clang: warning: argument unused during compilation: '-g'
clang: warning: argument unused during compilation: '-I .'
clang: warning: argument unused during compilation: '-D DO_DEBUG'
clang: warning: argument unused during compilation: '-D PCAP'
cc  -o horst average.o capture-pcap.o channel.o conf_options.o control.o display-channel.o display-essid.o display-filter.o display-help.o display-history.o display-main.o display-spectrum.o display-statistics.o display.o essid.o ieee80211_util.o ifctrl-ioctl.o listsort.o main.o network.o node.o protocol_parser.o protocol_parser_wlan.o radiotap/radiotap.o util.o wlan_util.o ifctrl-nl80211.o -lncurses -lm -lpcap -lnl-3 -lnl-genl-3
clang: error: no such file or directory: 'ifctrl-nl80211.o'

**Comment by JiantaoFu** [comment]
Thanks, I've succesfully compile the code with cmake, and made some changes to the code, however some functions are still not implemented. I will submit pull request later this week.

**Comment by br101** [comment]
That would be great! I'd recommend to create a new file "ifctrl-osx.c" or similar, and implement the OSX specific functionality there.

**Comment by br101** [comment]
Done. Thanks to @JiantaoFu :+1:
