### ISSUE TITLE
Wrong monitor type! Please use radiotap or prism2 headers

### ISSUE THREAD

**Issue by nemobis** [br101/horst#46]
What am I doing wrong?

```
$ rpm -qa | grep horst
horst-3.0-6.fc23.x86_64
$ uname -a
Linux 4.2.8-300.fc23.x86_64 #1 SMP Tue Dec 15 16:49:06 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
$ sudo horst -s
horst: Interface wlan0 not found: No such device
$ dmesg | grep wlan0
[    8.176151] iwlwifi 0000:03:00.0 wls1: renamed from wlan0
$ sudo horst -s -i wls1
Wrong monitor type! Please use radiotap or prism2 headers
$ lspci | grep WiFi
03:00.0 Network controller: Intel Corporation Ultimate N WiFi Link 5300
```

**Comment by br101** [comment]
RTFM

**Comment by nemobis** [comment]
Thanks for your reply. Which manual do you mean?

If you mean https://github.com/br101/horst/blob/master/README.md , do you mean the part about "set type monitor"? I had read it, but it didn't look relevant: «if the main interface (wlan0) is in use» didn't matter for this error, «If you want horst to be able to change channels (horst -s or channel_scan option)» maybe as it's about `-s` but I had the same error without.

Maybe you meant the man page, let's see: https://github.com/br101/horst/blob/master/horst.1 «options -C and -s do not work when virtual monitor interface is used» this seems to be a relevant passage, confirms the suspicion about the paragraph mentioned above.

So `ip link set wls1 down/up` per http://www.spinics.net/lists/linux-wireless/msg127023.html doesn't work for me (seems to work initially but then `horst` errors out saying it failed to switch to certain channels), but `sudo ifconfig wls1 down/up` per https://github.com/br101/horst/issues/2#issuecomment-37923347 did.

I hope the steps detailed in this report help other people with the same issue. :)

**Comment by br101** [comment]
Yes, I meant these... Maybe the ambiguity comes from the fact that the new documentation is not correct for older versions of horst. You seem to use version 3.0 (why so old?) so you need to set your interface to monitor mode before you use it. The current git version and next release will set monitor mode automatically, if possible.

**Comment by E3V3A** [comment]
I got this same error on a RPi3 Jesse when using the premade package which is already old. Most likely you have the WiFi already running so you need to shut it down first. Check with `ifconfig` then do something like:
```bash
sudo airmon-ng stop wlan1
...
sudo iw wlan1 set type monitor
sudo ifconfig wlan1 up
sudo iw wlan1 set channel 6
sudo horst -s -i wlan1
```
