### ISSUE TITLE
does not compile on OSX

### ISSUE THREAD

**Issue by antonmeyer** [br101/horst#47]
make OSX=1 results in
main.c:328:6: warning: logical not is only applied to the left hand side of this comparison [-Wlogical-not-parentheses]
        if (!conf.serveraddr[0] != '\0' && filter_packet(p)) {
            ^                   ~~
main.c:328:6: note: add parentheses after the '!' to evaluate the comparison first
        if (!conf.serveraddr[0] != '\0' && filter_packet(p)) {
            ^
             (                         )
main.c:328:6: note: add parentheses around left hand side expression to silence this warning
        if (!conf.serveraddr[0] != '\0' && filter_packet(p)) {
            ^
            (                  )
main.c:495:6: warning: logical not is only applied to the left hand side of this comparison [-Wlogical-not-parentheses]
        if (!conf.serveraddr[0] != '\0') {
            ^                   ~~
main.c:495:6: note: add parentheses after the '!' to evaluate the comparison first
        if (!conf.serveraddr[0] != '\0') {
            ^
             (                         )
main.c:495:6: note: add parentheses around left hand side expression to silence this warning
        if (!conf.serveraddr[0] != '\0') {
            ^
            (                  )
main.c:637:2: warning: implicit declaration of function 'clock_gettime' is invalid in C99 [-Wimplicit-function-declaration]
        clock_gettime(CLOCK_MONOTONIC, &stats.stats_time);
        ^
main.c:637:16: error: use of undeclared identifier 'CLOCK_MONOTONIC'
        clock_gettime(CLOCK_MONOTONIC, &stats.stats_time);
                      ^
main.c:638:16: error: use of undeclared identifier 'CLOCK_MONOTONIC'
        clock_gettime(CLOCK_MONOTONIC, &the_time);
                      ^
main.c:723:17: error: use of undeclared identifier 'CLOCK_MONOTONIC'
                clock_gettime(CLOCK_MONOTONIC, &the_time);
                              ^
main.c:760:16: error: use of undeclared identifier 'CLOCK_MONOTONIC'
        clock_gettime(CLOCK_MONOTONIC, &stats.stats_time);
                      ^
3 warnings and 4 errors generated.
make: *** [main.o] Error 1

**Comment by br101** [comment]
I fixed the !conf.serveraddr[0] warnings but for clock_gettime someone with OS X should fix it.

Check
- https://gist.github.com/jbenet/1087739
- https://gist.github.com/alfwatt/3588c5aa1f7a1ef7a3bb

**Comment by aaaaalbert** [comment]
For the record, it's 7da1869fd6e4f4ef16f105075c54462392cb7ec5 that fixed the `conf.serveradd[0]` warning; c71563a985ebae941219d8ff7920ba1bc027f396 introduced the `clock_gettime` problem. I'll see if I can tackle the clock issue.

**Comment by aaaaalbert** [comment]
I tried out the proposed workarounds for `clock_gettime` on Mac in a branch based on `stable` [over here](https://github.com/aaaaalbert/horst/tree/mach_clock_gettime). Compiles fine, binary runs, etc.

However, one issue that I see is that using OS X's `clock_get_time` as a replacement for `clock_gettime` breaks the wallclock display in the bottom right of `horst`'s GUI. The problem is that `clock_get_time` returns something like the uptime of the machine minus the time it slept, rather than the seconds elapsed since the Epoch...

**Comment by br101** [comment]
Thanks! The time display on screen is a very minor issue. If you create a pull-request I'd merge it into stable in its current state (minus the "test_mach_clock_gettime.c") and we can iron out the display clock later. I suppose display clock should always be "real wall time" so monotonic clock doesnt make sense there.

**Comment by aaaaalbert** [comment]
Sure, just let me clean up the references and code style a bit.

**Comment by aaaaalbert** [comment]
@br101, here you go.

**Comment by br101** [comment]
Thanks a lot!

Do you think you could add a similar thing to libuwifi? OSX support in uwifi is still horribly broken though, and platform depended code needs a better structure, but the timing issue should be simpler there since I just need plat_time_usec() to return monotonic time in usec. No wrapper needed.

**Comment by aaaaalbert** [comment]
Welcome! Let me now if I should send a PR against `master` too.

Re `libuwifi`, I can sure take a look at that as well.

**Comment by br101** [comment]
ATM there are still `clock_gettime()` calls in master, but this is WIP and if possible finally it should only use the platform functions `plat_time_usec()` from libuwifi. As I said there is still much work to do in libuwifi to make OSX (and general platform specific code) support better... Danke & Servus! :)
