### ISSUE TITLE
How to start using CLI in channel auto?

### ISSUE THREAD

**Issue by gazambuja** [br101/horst#49]
How to start horst to change channels automatic?
I try 

> horst -x channel_auto=1 -i mon0 -f NULL -f PROBE -f ASSOC without success.

**Comment by br101** [comment]
Hi! You could use the -s switch, but that also puts the view into "spectrum analyzer" as well.

    sudo ./horst -i wlp3s0 -s

If you use the latest version (5.0) you can specify channel_scan in the config file (/etc/horst.conf)

BTW: -x is only used to control another instance of horst which has before been started with -X
BTW2: channel_auto has been renamed to channel_scan in horst 5.0
