### ISSUE TITLE
Trying to build Horst for Raspberry PI

### ISSUE THREAD

**Issue by henrikkorsgaard** [br101/horst#52]
I cloned the repository and did the suggested `make` from the readme guide. Here is my output -- any idea what I'm doing wrong?

``echo '-std=gnu99 -Wall -Wextra -g -I.' | cmp -s - .buildflags || echo '-std=gnu99 -Wall -Wextra -g -I.' > .buildflags
cc -std=gnu99 -Wall -Wextra -g -I.   -c -o conf_options.o conf_options.c
conf_options.c:25:24: fatal error: uwifi/util.h: No such file or directory
 #include <uwifi/util.h>
                        ^
compilation terminated.
<builtin>: recipe for target 'conf_options.o' failed
make: *** [conf_options.o] Error 1
``

Best,
Henrik

**Comment by Duncaen** [comment]
Looks like https://github.com/br101/horst/commit/d27e8c6d0d9377d571c21b04b1fad6cc508e4902 moved code https://github.com/br101/libuwifi which you need to build before horst.
But this is not part of a release yet, I would use a tagged version instead of master.

**Comment by br101** [comment]
Yes, Duncaen is right. I am heavily restructuring the code now, moving re-usable functionality from horst to libuwifi. 'master' branch should work, but If you don't want to bother with that, please use the 'stable' branch.
