### ISSUE TITLE
Install man files with make install (and rename)

### ISSUE THREAD

**Issue by E3V3A** [br101/horst#58]
Please consider installing the `man` files using a make install. Also add how to install the files manually. 

The horst *man* file has the wrong name. To install correctly use something like:
```bash
# Note wrong name here, referring to wrong manual page of 1 instead of 8.
cp horst.1 horst.8
gzip horst.8
sudo cp horst.8.gz /usr/share/man/man8/horst.8.gz
gzip horst.conf.5
sudo cp horst.conf.5 /usr/share/man/man5/horst.conf.5.gz
```

**Comment by br101** [comment]
Done in a0df502980a7993a7fd4a039df4ec876bebb89b6 and df41a36f903682ab3a68cfc529a3656ee29a94ca
