### ISSUE TITLE
Broken link to submodule libuwifi

### ISSUE THREAD

**Issue by ojag** [br101/horst#59]
If you issue the following command:

> git clone git://github.com/br101/horst.git horst --recursive

it will fail to clone the libuwifi submodule and produce the following error:

> fatal: reference is not a tree: 013ba18f9f2589d9478009a3b4abebfb09065054
> Unable to checkout '013ba18f9f2589d9478009a3b4abebfb09065054' in submodule path 'libuwifi'

It is easy to see why this occurs if you go to [https://github.com/br101/horst](url) and click on the link to the libuwifi submodule ([https://github.com/br101/libuwifi/tree/013ba18f9f2589d9478009a3b4abebfb09065054](url))

I was able to manually clone libuwifi using:

> git clone git://github.com/br101/libuwifi libuwifi --recursive

However, when I tried to checkout the commit (013ba18f9f2589d9478009a3b4abebfb09065054) with:

> git checkout 013ba18f9f2589d9478009a3b4abebfb09065054

it reproduces the error:

> fatal: reference is not a tree: 013ba18f9f2589d9478009a3b4abebfb09065054

I think the problem may be that this particular commit of libuwifi has not been pushed to Github. This means the parent module (horst) is referencing a commit that doesn't exist on Github yet.

**Comment by br101** [comment]
Sorry, forgot to push. Should be fixed now
