### ISSUE TITLE
Segfault since 8345a13

### ISSUE THREAD

**Issue by alexandreyc** [br101/horst#63]
Hi,

I've encountered a segfault which seems to be introduced by commit 8345a13 (I found out this using git bisect). 

The command I use is the following: `horst -i mon0 -q -o /tmp/stream -f PROBRQ` where `/tmp/stream` is a named pipe. The command starts correctly and after a few seconds it segfaults. Notice that sometimes it doesn't segfault but it's just frozen and output nothing. Debug log doesn't bring much interesting information...

Let me know if you need more informations, I'm also working on it.

**Comment by br101** [comment]
Does the problem also happen when you use -o /dev/stdout? Using that I can't reproduce it here...

**Comment by alexandreyc** [comment]
Same problem with `-o /dev/stdout`. 

After investigations I think I've found one problem: https://github.com/br101/libuwifi/blob/985e05797a04374ebd5d7d0ef88e18dc5f326861/core/essid.c#L33

The foreach loop is infinite sometimes. It looks like this diff is the cause of the problem: https://github.com/br101/libuwifi/compare/acfabe9628d8a03984133d6b970396560adca8f6...985e05797a04374ebd5d7d0ef88e18dc5f326861#diff-5f63bdd3cd38b6b2cc34c24bfd776cb1

Since I'm not a wifi expert, can you check the condition before the `continue` ? 

Thanks

**Comment by alexandreyc** [comment]
This could explain why the program is sometimes frozen, but it actually does not fully explain the segfault. I'm still on it.

**Comment by br101** [comment]
Hi! I think I have fixed this. Can you try to reproduce it with the version of today (9d360aabda65bfd3ae3e9261c4107fa0abb65657)?

**Comment by alexandreyc** [comment]
Hello, I no longer have access to the hardware I was using for testing. I will ask a former colleague to see if he can check.

**Comment by br101** [comment]
Code changed
