### ISSUE TITLE
Can't set 3 digit channels

### ISSUE THREAD

**Issue by zsaile** [br101/horst#65]
When in the main interface of host, i hit 'c' to get to the Channel menu, and i then press 'm' to set a channel manually, it only allows me to enter a 2 digit channel. I cannot type in for example channel 104. However if i set the 'automatically channel change' option i do see it goes to these channel. 

Can the code be updated to allow for channels to be manually set to allow for 3 digit channels? Basically can't manually set to channel 100-165

**Comment by br101** [comment]
Fixed since version 5.0 (stable)
