### ISSUE TITLE
Compilation and dependencies questions.

### ISSUE THREAD

**Issue by ssinfod** [br101/horst#68]
Hello, 

I have a general question about the compilation and dependencies of horst.

Can you explain what is the difference between using libnl, libpcap and libuwifi ?
I'm a bit confused regarding the difference of each library ?  (advandatage/disadvantage)

I also don't understand the comment in the "README.md"
"_To experimentally build using libpcap (note that libpcap on Linux is not necessary and not recommended) use (Broken right now!):_"

What is broken with libpcap?

Is there more than one way to capture the Wifi packet in horst ?
What is the recommended library in horst ?
Can I use two capture libraries at the same time with horst ? (ex: make PCAP=1  ... does it compile with PCAP=1 and LIBNL=1 ?)

thanks for your comments.

**Comment by br101** [comment]
Each library is for a different "task", shortly:

* libnl is used to communicate with the wireless stack of linux. i.e. setting monitor mode, setting channels

* libpcap is an *alternative* way to capture packets, normally horst captures by using a "raw" socket, but this works on linux only (main target).

* libuwifi was split out of horst recently. it contains the main parts of wifi capturing and analyzing, while "horst" is mostly providing the (text) GUI.

please google for each library and see its project site to understand more of it.

**Comment by ssinfod** [comment]
OK, thanks for the answer.

One last question:
Would it be possible to add an option in horst or libuwifi to create a .pcap file as an output ?
I understand that libpcap is optionnal and horst typically use libuwifi but it would be great to have the 
"packet-level" binary file for debugging purpose.

Is this a possible option ?
Otherwise is there something similar in the current output file ?

Thanks,

**Comment by br101** [comment]
Possible: yes. You'd need to revive pcap support first and then use it to write the pcap file.
