### ISSUE TITLE
OLSR2 support?

### ISSUE THREAD

**Issue by L337hium** [br101/horst#7]
Would it be possible for you to implement OLSR2 support?

**Comment by br101** [comment]
Possible: yes... But it depends on what level of support. Should be pretty easy to just recognize OLSRv2 nodes, but a bit more complicated if you want to know more of the OLSRv2 details (e.g. number of neighbours, MPRs, etc..)...

**Comment by L337hium** [comment]
I thought about support like for olsr, batman-adv, etc... OLSRd2 is still under development but I think the protocol part is done at the time. I can announce this request also on the wireless community weekend and on the battlemesh-list, maybe there are some dev who can give more details what would be useful.

**Comment by br101** [comment]
Should be easy to do if you look at the end of protocol_parser.c. For basic detection it's enough to know the port numbers, for more you'd have to parse the OLSRv2 packet itself.

**Comment by L337hium** [comment]
Thanks, I will take a look at this!
