### ISSUE TITLE
quiet mode 

### ISSUE THREAD

**Issue by henrikkorsgaard** [br101/horst#71]
Hi,
I am running horst version 5.1-pre built on raspbian (PI Zero). I run horst as a server and connect to it with a custom Java client. 

If I run Horst as ``horst -i wlan0 -N -p 4260`` everything is fine. I get the the data over the network as expected and the user interfaces shows the data as well.

However, if I try quiet mode (both ``horst -i wlan0 -N -p 4260 -q`` and ``horst -i wlan0 -q``) I get the following errors before exit:

```
Try to set max channel width HT40
nl80211 message failed: Object busy
ERROR: Failed to set CH 6 (2437 MHz) HT40+ center 2447
nl80211 message failed: Object busy
ERROR: Failed to set CH 6 (2437 MHz) HT40- center 2427
horst: failed to change the initial channel number: No such device
```
Is this expected?

I have not tried with the stable version or a new build, as I want some feedback before initiating a new build on a raspberry pi.

Thank you

**Comment by br101** [comment]
This probably means that your interface is in use otherwise and could not be set to monitor mode. Probably a "horst0" interface is created and in this case we can not change channels or channel width.
