### ISSUE TITLE
use "vX.Y" tag names (aka semantic versioning)

### ISSUE THREAD

**Issue by anarcat** [br101/horst#75]
Hi!

Horst currently uses a tagging scheme like `version-X.Y`. this makes GitHub generate a tarball (and its content) that is weirdly named:

```
$ tar zft ../version-5.0.tar.gz  | head -1
horst-version-5.0/
```

If you would use the more conventional `vX.Y` or simply `X.Y` as a naming scheme, Github would strip away that `v` letter an create a more reasonable tarball:

```
$ tar zft ../build-area/horst-5.0.tar.gz  | head -1
horst-5.0/
```

This would be useful for the Debian package I am maintaining as it would make it possible to reproducibly rebuild the original tarball from the Git source more easily.

Thanks!

**Comment by br101** [comment]
Sorry for the long delay. Thanks for the suggestion - will do so from now (v5.1) on.
