### ISSUE TITLE
Installing horst from master branch fails on rpi3

### ISSUE THREAD

**Issue by inamiitb** [br101/horst#77]
I cloned  master branch on raspberry pi using 
`git clone --recursive https://github.com/br101/horst `
but the build fails with the error:
```
pi@rpi-inam:~/horst_master $ make
  CC      conf_options.c
conf_options.c:25:24: fatal error: uwifi/util.h: No such file or directory
 #include <uwifi/util.h>
                        ^
compilation terminated.
Makefile.default:62: recipe for target 'build/conf_options.o' failed
make: *** [build/conf_options.o] Error 1
```

P.S. I am able to enable monitor mode in Raspberry Pi 3 using nexmon. When I install horst from the stable branch, it gets installed, but exits with "Floating point exception error" after running for a while.

**Comment by br101** [comment]
Please try the latest version from today and use `make V=1 LIBUWIFI_SUBMOD=1`

**Comment by inamiitb** [comment]
Thank you for reply.

The make V=1 LIBUWIFI_SUBMOD=1  proceeds to the end, whose output I attached as file
[horstmake.txt](https://github.com/br101/horst/files/1375395/horstmake.txt)

But make install throws following errors:
pi@rpi-inam:~/horst_new/horst $ make install
mkdir -p /usr/local/sbin/
mkdir -p /usr/local/etc
mkdir -p /usr/local/man/man8/
mkdir -p /usr/local/man/man5
cp horst /usr/local/sbin/
cp: cannot stat 'horst': No such file or directory
Makefile:69: recipe for target 'install' failed
make: *** [install] Error 1

**Comment by br101** [comment]
Need to fix that too. In the mean time try running horst from the build directory

**Comment by br101** [comment]
Now it should work:

    make V=1 LIBUWIFI_SUBMOD=1 install

**Comment by inamiitb** [comment]
It is still not working.

I get the following:
pi@rpi-inam:~/horst_new/horst $ make V=1 LIBUWIFI_SUBMOD=1 install
mkdir -p /usr/local/sbin/
mkdir -p /usr/local/etc
mkdir -p /usr/local/man/man8/
mkdir -p /usr/local/man/man5
cp horst /usr/local/sbin/
cp: cannot stat 'horst': No such file or directory
Makefile:69: recipe for target 'install' failed
make: *** [install] Error 1

**Comment by warlock20** [comment]
` make V=1 LIBUWIFI_SUBMOD=1` build every inside the build folder. 

`cp horst /usr/local/sbin/` is looking for horst file inside the parent folder, modify your makefile to 
`cp build/horst /usr/local/sbin/`

**Comment by warlock20** [comment]
``cp horst /usr/local/sbin/` trying to copy the horst file from the parent directory while the build is located inside the build folder... Modify the Makefile..I think its already modified.. Try new version

**Comment by inamiitb** [comment]
Build worked with the modified make. But now horst is unable to start, and throws the following error:

> pi@rpi-inam:~ $ sudo horst -i wlan0
> horst: error while loading shared libraries: libuwifi.so.1: cannot open shared object file: No such file or directory

**Comment by br101** [comment]
Have you tried my latest version? It should be fixed there.

Does horst run, if you start it from the build directory?

If not, please try to run with

    sudo LD_LIBRARY_PATH="/usr/local/lib" horst

**Question to the general public: Should I rather link libuwifi statically to avoid these kinds of problems?**

**Comment by inamiitb** [comment]
Yeah. and it runs from the build directory. But is not running from normal command line.

For building I did the following:

```
pi@rpi-inam:~/horst_new/horst $ git pull
Updating e6942d8..50f905e
Fast-forward
Makefile | 7 ++++++-
config.h | 3 ---
2 files changed, 6 insertions(+), 4 deletions(-)

```

 ```
pi@rpi-inam:~/horst_new/horst $ make clean
  CLEAN
 pi@rpi-inam:~/horst_new/horst $ make V=1 LIBUWIFI_SUBMOD=1
```

Its output is here: 
[make-error-2017-10-12.txt](https://github.com/br101/horst/files/1378854/make-error-2017-10-12.txt)

```
pi@rpi-inam:~/horst_new/horst $ sudo make install
mkdir -p /usr/local/sbin/
mkdir -p /usr/local/etc
mkdir -p /usr/local/man/man8/
mkdir -p /usr/local/man/man5
cp build/horst /usr/local/sbin/
cp horst.conf /usr/local/etc/
gzip horst.8 -c > /usr/local/man/man8/horst.8.gz
gzip horst.conf.5 -c > /usr/local/man/man5/horst.conf.5.gz

```
Finally, when I run horst, I get this:
```
pi@rpi-inam:~/horst_new/horst $ sudo horst -i wlan0
horst: error while loading shared libraries: libuwifi.so.1: cannot open shared object file: No such file or directory
```

**Comment by br101** [comment]
sudo make V=1 LIBUWIFI_SUBMOD=1 install

**Comment by inamiitb** [comment]
Great! It worked.

Thanks a lot.
I don't know whether I should ask it here...
I want to run horst when my rpi is also running as an AP. i.e., can I make another virtual interface that runs in monitor mode, while on the actual interface AP runs?
Currently, for running host on interface wlan0, I have to first manually turn the interface wlan0 to monitor mode using the nexmon's utility as
`nexutil -m2`
If I don't do the above step, horst does not run. For example, running horst when wlan0 is in managed mode gives the following error:
```
pi@rpi-inam:~ $ sudo horst -i wlan0
Set 'quiet'
- Writing to outfile horst.out
nl80211 message failed: Operation not supported
nl80211 message failed: Operation not supported
horst: failed to add virtual monitor interface: No such device
```

Any help?
Kind regards.
Inam

**Comment by br101** [comment]
Well, usually, well written linux wireless drivers can add a virtual monitor interface, for example ath9k and others. The driver for the wlan chip in the raspberry pi officially does not support monitor mode at all! Nexmon is a hack to add monitor mode, and it seems it can only either do monitor mode or AP mode (I personally have not used it yet).
