### ISSUE TITLE
SNR output 99 dB  

### ISSUE THREAD

**Issue by tibrado** [br101/horst#78]
Hi, 
     I installed Horst on Raspberry Pi 3 B Jessie OS. Running the program is fine except the Signal output is 99 dB for every ESSID. When the Horst is used on my Openwrt OS I receive what I presume to be accurate signal levels. 
* The Horst version on Opnewrt is a little out date. Therefore I believe the problem is with the new version*

**Comment by br101** [comment]
It may be a probelm with your wlan driver... Is the same WiFi chipset in use? Do you use the rpi3 internal WiFi which as far as I know has to be hacked to add monitor mode...?

**Comment by tibrado** [comment]
Hey Br101
                 I am using a usb dongle with Ralinks RT5370 chipset. It is able supports monitor mode.

**Comment by tibrado** [comment]
Thanks for the quick reply btw.

**Comment by br101** [comment]
I dont think there is a general problem with rssi information in the current version, it works here with ath9k.

Can you try to compile horst with DEBUG=1 and run with -D and check the radiotap signal output...?

**Comment by br101** [comment]
Verified with a RT5370 on Rpi3 with Rasbian (Linux raspberrypi 4.9.41-v7+) and SNR values are OK. Please post your kernel version.

**Comment by br101** [comment]
any results from your side? did you try earlier horst versions on the same distro? can you provide the output of compiling with DEBUG=1 and running with -D?
