### ISSUE TITLE
support ubus in OpenWRT/Lede

### ISSUE THREAD

**Issue by zhaojh329** [br101/horst#79]
support  ubus in OpenWRT/Lede...

**Comment by br101** [comment]
hi, no problem, but what do you want to do over ubus? configure? get statistics? get results? nodes? packets???

**Comment by zhaojh329** [comment]
I have implenmented it.

Usage in libubus-lua:

#!/usr/bin/lua

-- iw wlan0 interface add mon0 type monitor
-- ifconfig mon0 up

require "ubus"
require "uloop"

uloop.init()

local conn = ubus.connect()
if not conn then
	error("Failed to connect to ubus")
end

local subscriber = {
	notify = function(msg, method)
		print(msg.timestamp,
			method, 
			"src:" .. msg.src, "dst:" .. msg.dst,
			"bssid:" .. msg.bssid,
			"signal:" .. msg.signal,
			"channel:" .. msg.channel,
			"essid:" .. msg.essid,
			msg.encryption)
	end,
}

conn:subscribe("horst", subscriber)

uloop.run()

**Comment by br101** [comment]
do you want to make a pull request?

**Comment by zhaojh329** [comment]
I will do it.
