### ISSUE TITLE
Error compiling master branch - too few arguments to function ‘uwifi_channel_width_string’

### ISSUE THREAD

**Issue by djjerdog** [br101/horst#81]
CC      conf_options.c
cc -std=gnu99 -Wall -Wextra -g -I. -I./build/include/ -MD -DVERSION=\"version-5.0-105-g29bee88\"  -o build/conf_options.o -c conf_options.c
  CC      control.c
cc -std=gnu99 -Wall -Wextra -g -I. -I./build/include/ -MD -DVERSION=\"version-5.0-105-g29bee88\"  -o build/control.o -c control.c
  CC      display-channel.c
cc -std=gnu99 -Wall -Wextra -g -I. -I./build/include/ -MD -DVERSION=\"version-5.0-105-g29bee88\"  -o build/display-channel.o -c display-channel.c
display-channel.c: In function ‘update_channel_win’:
display-channel.c:50:4: error: too few arguments to function ‘uwifi_channel_width_string’
    uwifi_channel_width_string(bp->max_chan_width));
    ^
In file included from main.h:29:0,
                 from display-channel.c:28:
./build/include/uwifi/channel.h:69:13: note: declared here
 const char* uwifi_channel_width_string(enum uwifi_chan_width w, int ht40p);
             ^
display-channel.c: In function ‘channel_input’:
display-channel.c:171:4: warning: implicit declaration of function ‘uwifi_channel_fix_center_freq’ [-Wimplicit-function-declaration]
    uwifi_channel_fix_center_freq(&conf.intf.channel_set, set_ht40plus);
    ^
Makefile.default:62: recipe for target 'build/display-channel.o' failed
make: *** [build/display-channel.o] Error 1

**Comment by br101** [comment]
please update libuwifi

**Comment by br101** [comment]
sorry, yes i had to update the libuwifi submodule. should work now if you update with

    git pull
    git submodule update
