### ISSUE TITLE
Unable to scan beyond channel 1

### ISSUE THREAD

**Issue by jasonyates** [br101/horst#83]
I have HORST running on a RPi 2 with a USB RTL8812AU 802.11a/b/g/n/ac connected.

When running HORST I only see output from channel 1. Attempting to channel scan or set a channel other than 1 results in an error

ERROR: Failed to set CH 136 (5680 MHz) HT40-                                                       
ERROR: Failed to set CH 136 (5680 MHz) HT40+  
ERROR: Failed to set CH 140 (5700 MHz) HT40- 
ERROR: Failed to set CH 149 (5745 MHz) HT40+
ERROR: Failed to set CH 153 (5765 MHz) HT40-  
nl80211 message failed: Operation not supported

**Comment by br101** [comment]
- is the whole interface in monitor mode or did horst add a virtual horst0 interface?
- can you set other channels with `iw wlan0 set channel x`?
- what is your wlan driver? Last time I checked AC drivers other than ath10k and intel did not work well in monitor mode yet
