### ISSUE TITLE
UBUS

### ISSUE THREAD

**Issue by Gobiviswa** [br101/horst#84]
Hi,

How to get ifconfig data of Openwrt Device from UBUS ?

**Comment by br101** [comment]
`ubus call network.interface.xxx status` or something like this.

Unrelated to horst, closing.

**Comment by Gobiviswa** [comment]
i am not getting the IFCONFIG data when i am using ubus call network.interface.xxx status. It is not giving netmask address and all. Can anyone help me to get ifconfig data through ubus call?
