### ISSUE TITLE
Segmentation fault when trying to connect Client

### ISSUE THREAD

**Issue by Virlevanz** [br101/horst#88]
Hello there,
i have a problem with the client, i can't connect it to the horst server.
I want to start horst as "Server" and connect a client on a Raspberry Pi 3. I test both versions, the stable version and the master version of horst. I allways get the same error.

wlan1 = extern wlan usb adapter ( Alfa Network) 
          = set to monitor mode

wlan0 = onboard wlanchip 
          = nothing has been changed

Here you see: Horst starts without any problems as Server
`sudo horst -c /etc/horst_server.conf
Using config file '/etc/horst_server.conf'
Set 'interface' = 'wlan1'
Set 'channel_scan'
Set 'server'
Set 'quiet'
Got 1 Bands, 13 Channels:
1  : 2412 HT40+
2  : 2417 HT40+
3  : 2422 HT40+
4  : 2427 HT40+
5  : 2432 HT40+-
6  : 2437 HT40+-
7  : 2442 HT40+-
8  : 2447 HT40+-
9  : 2452 HT40+-
10 : 2457 HT40-
11 : 2462 HT40-
12 : 2467 HT40-
13 : 2472 HT40-
Max PHY rate: 150 Mbps
Initializing server port 4444
`
Here you see: how i try to connect the client to the server, i try to connect with the interface wlan0 and wlan1 allways the same error "Segmentation fault"
` sudo horst
Set 'interface' = 'wlan0'
Set 'client' = '192.168.66.100'
Set 'quiet'
Connecting to server 192.168.66.100 port 4444
Connected to server 192.168.66.100
Max PHY rate: 0 Mbps
Segmentation fault
`
At the same time on the serverscreen
`Accepting client
Client has closed
Initializing server port 4444
`

gdb shows an error at the lib but it still doesn't help me to solve the problem
` sudo gdb horst
GNU gdb (Raspbian 7.12-6) 7.12.0.20161007-git
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "arm-linux-gnueabihf".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from horst...done.
(gdb) run -d -L debug
Starting program: /home/pi/horst_system/horst/horst -d -L debug
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
Set 'interface' = 'wlan0'
Set 'client' = '192.168.66.100'
Set 'quiet'
Connecting to server 192.168.66.100 port 4444
Connected to server 192.168.66.100
Max PHY rate: 0 Mbps

Program received signal SIGSEGV, Segmentation fault.
0x76fa0050 in ?? () from /lib/arm-linux-gnueabihf/libncurses.so.5
(gdb) bt
#0  0x76fa0050 in ?? () from /lib/arm-linux-gnueabihf/libncurses.so.5
#1  0x76f9be24 in vwprintw () from /lib/arm-linux-gnueabihf/libncurses.so.5
#2  0x00000000 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb)
`

Anybody here have an idea to solve the problem?

**Comment by br101** [comment]
fixed
