### ISSUE TITLE
scan fails due to trying to scan Channel 10 @ +40 MHz

### ISSUE THREAD

**Issue by djjerdog** [br101/horst#89]
Is there away to specify which channels are scanned in the scan mode? The adapter I'm using does not support 40 MHz on 2.4 GHz, due to this HORST always errors when I select scan.

Failed to set CH 10 (2457 MHz) HT40+ center 2467 after 3094ms
next channel not ok
Set CH 10 (2457 MHz) HT40+
Failed to set CH 10 (2457 MHz) HT40+ center 2467 after 3096ms
next channel not ok               
Set CH 10 (2457 MHz) HT40+
Failed to set CH 10 (2457 MHz) HT40+ center 2467 after 3099ms 
next channel not ok
Set CH 10 (2457 MHz) HT40+
Failed to set CH 10 (2457 MHz) HT40+ center 2467 after 3102ms
next channel not ok
Set CH 10 (2457 MHz) HT40+
Failed to set CH 10 (2457 MHz) HT40+ center 2467 after 3105ms
next channel not ok
Set CH 10 (2457 MHz) HT40+
Failed to set CH 10 (2457 MHz) HT40+ center 2467 after 3107ms
next channel not ok
Set CH 10 (2457 MHz) HT40+
Failed to set CH 10 (2457 MHz) HT40+ center 2467 after 3110ms
Channel change failed. Disabling scan on 'wlan0'

**Comment by br101** [comment]
have you tried the latest version of libuwifi and horst? there have been some fixes regarding this

**Comment by djjerdog** [comment]
I'm using version-5.0-106-g13ab061 using libuwifi v0.1-76-gc270929

Whenever I run a scan it errors out everytime when it gets to channel 10, because 10 @ +40 MHz is not valid (at least not in the US Reg domain). If I manually set the channel to 11 @ -40 MHz and restart the scan it will run until it gets back to channel 10 and then errors out.

**Comment by br101** [comment]
which chipset is this? can you send me the channel list output when horst starts? and the output of "sudo iw phy0 info" please

**Comment by djjerdog** [comment]
I'm using a Realtek RTL8812au chipset with the following driver https://github.com/aircrack-ng/rtl8812au, specifically the v5.2.20 branch

~$ sudo horst
Could not open config file '/etc/horst.conf'
SURVEY
Got 2 Bands, 39 Channels:
1  : 2412 HT40+
2  : 2417 HT40+
3  : 2422 HT40+
4  : 2427 HT40+
5  : 2432 HT40+-
6  : 2437 HT40+-
7  : 2442 HT40+-
8  : 2447 HT40+-
9  : 2452 HT40+-
10 : 2457 HT40+-
11 : 2462 HT40-
12 : 2467 HT40-
13 : 2472 HT40-
14 : 2484 HT20
36 : 5180 VHT80+
40 : 5200 VHT80+-
44 : 5220 VHT80+-
48 : 5240 VHT80+-
52 : 5260 VHT80+-
56 : 5280 VHT80+-
60 : 5300 VHT80+-
64 : 5320 VHT80-
100: 5500 VHT80+
104: 5520 VHT80+-
108: 5540 VHT80+-
112: 5560 VHT80+-
116: 5580 VHT80+-
120: 5600 VHT80+-
124: 5620 VHT80+-
128: 5640 VHT80+-
132: 5660 VHT80+-
136: 5680 VHT80+-
140: 5700 VHT80+-
144: 5720 VHT80-
149: 5745 VHT80+
153: 5765 VHT80+-
157: 5785 VHT80+-
161: 5805 VHT80+-
165: 5825 HT40-
Current channel: CH 36 (5180 MHz) HT20
Set max channel width CH 36 (5180 MHz) VHT80 (center 5210)
Max PHY rate: 867 Mbps

------------------------------------------------------------------

$ sudo iw phy0 info
Wiphy phy0
	max # scan SSIDs: 9
	max scan IEs length: 2304 bytes
	max # sched scan SSIDs: 0
	max # match sets: 0
	max # scan plans: 1
	max scan plan interval: -1
	max scan plan iterations: 0
	Retry short limit: 7
	Retry long limit: 4
	Coverage class: 0 (up to 0m)
	Supported Ciphers:
		* WEP40 (00-0f-ac:1)
		* WEP104 (00-0f-ac:5)
		* TKIP (00-0f-ac:2)
		* CCMP-128 (00-0f-ac:4)
	Available Antennas: TX 0 RX 0
	Supported interface modes:
		 * IBSS
		 * managed
		 * AP
		 * monitor
		 * P2P-client
		 * P2P-GO
	Band 1:
		Capabilities: 0x19f2
			HT20/HT40
			Static SM Power Save
			RX Greenfield
			RX HT20 SGI
			RX HT40 SGI
			TX STBC
			RX STBC 1-stream
			Max AMSDU length: 7935 bytes
			DSSS/CCK HT40
		Maximum RX AMPDU length 65535 bytes (exponent: 0x003)
		Minimum RX AMPDU time spacing: 16 usec (0x07)
		HT Max RX data rate: 952 Mbps
		HT TX/RX MCS rate indexes supported: 0-15
		Bitrates (non-HT):
			* 1.0 Mbps
			* 2.0 Mbps
			* 5.5 Mbps
			* 11.0 Mbps
			* 6.0 Mbps
			* 9.0 Mbps
			* 12.0 Mbps
			* 18.0 Mbps
			* 24.0 Mbps
			* 36.0 Mbps
			* 48.0 Mbps
			* 54.0 Mbps
		Frequencies:
			* 2412 MHz [1] (20.0 dBm)
			* 2417 MHz [2] (20.0 dBm)
			* 2422 MHz [3] (20.0 dBm)
			* 2427 MHz [4] (20.0 dBm)
			* 2432 MHz [5] (20.0 dBm)
			* 2437 MHz [6] (20.0 dBm)
			* 2442 MHz [7] (20.0 dBm)
			* 2447 MHz [8] (20.0 dBm)
			* 2452 MHz [9] (20.0 dBm)
			* 2457 MHz [10] (20.0 dBm)
			* 2462 MHz [11] (20.0 dBm)
			* 2467 MHz [12] (20.0 dBm) (no IR)
			* 2472 MHz [13] (20.0 dBm) (no IR)
			* 2484 MHz [14] (20.0 dBm) (no IR)
	Band 2:
		Capabilities: 0x19f2
			HT20/HT40
			Static SM Power Save
			RX Greenfield
			RX HT20 SGI
			RX HT40 SGI
			TX STBC
			RX STBC 1-stream
			Max AMSDU length: 7935 bytes
			DSSS/CCK HT40
		Maximum RX AMPDU length 65535 bytes (exponent: 0x003)
		Minimum RX AMPDU time spacing: 16 usec (0x07)
		HT Max RX data rate: 952 Mbps
		HT TX/RX MCS rate indexes supported: 0-15
		VHT Capabilities (0x03c13aa2):
			Max MPDU length: 11454
			Supported Channel Width: neither 160 nor 80+80
			short GI (80 MHz)
			TX STBC
			SU Beamformer
			SU Beamformee
			+HTC-VHT
		VHT RX MCS set:
			1 streams: MCS 0-9
			2 streams: MCS 0-9
			3 streams: not supported
			4 streams: not supported
			5 streams: not supported
			6 streams: not supported
			7 streams: not supported
			8 streams: not supported
		VHT RX highest supported: 867 Mbps
		VHT TX MCS set:
			1 streams: MCS 0-9
			2 streams: MCS 0-9
			3 streams: not supported
			4 streams: not supported
			5 streams: not supported
			6 streams: not supported
			7 streams: not supported
			8 streams: not supported
		VHT TX highest supported: 867 Mbps
		Bitrates (non-HT):
			* 6.0 Mbps
			* 9.0 Mbps
			* 12.0 Mbps
			* 18.0 Mbps
			* 24.0 Mbps
			* 36.0 Mbps
			* 48.0 Mbps
			* 54.0 Mbps
		Frequencies:
			* 5180 MHz [36] (20.0 dBm) (no IR)
			* 5200 MHz [40] (20.0 dBm) (no IR)
			* 5220 MHz [44] (20.0 dBm) (no IR)
			* 5240 MHz [48] (20.0 dBm) (no IR)
			* 5260 MHz [52] (20.0 dBm) (no IR, radar detection)
			* 5280 MHz [56] (20.0 dBm) (no IR, radar detection)
			* 5300 MHz [60] (20.0 dBm) (no IR, radar detection)
			* 5320 MHz [64] (20.0 dBm) (no IR, radar detection)
			* 5500 MHz [100] (20.0 dBm) (no IR, radar detection)
			* 5520 MHz [104] (20.0 dBm) (no IR, radar detection)
			* 5540 MHz [108] (20.0 dBm) (no IR, radar detection)
			* 5560 MHz [112] (20.0 dBm) (no IR, radar detection)
			* 5580 MHz [116] (20.0 dBm) (no IR, radar detection)
			* 5600 MHz [120] (20.0 dBm) (no IR, radar detection)
			* 5620 MHz [124] (20.0 dBm) (no IR, radar detection)
			* 5640 MHz [128] (20.0 dBm) (no IR, radar detection)
			* 5660 MHz [132] (20.0 dBm) (no IR, radar detection)
			* 5680 MHz [136] (20.0 dBm) (no IR, radar detection)
			* 5700 MHz [140] (20.0 dBm) (no IR, radar detection)
			* 5720 MHz [144] (20.0 dBm) (no IR, radar detection)
			* 5745 MHz [149] (20.0 dBm) (no IR)
			* 5765 MHz [153] (20.0 dBm) (no IR)
			* 5785 MHz [157] (20.0 dBm) (no IR)
			* 5805 MHz [161] (20.0 dBm) (no IR)
			* 5825 MHz [165] (20.0 dBm) (no IR)
			* 5845 MHz [169] (disabled)
			* 5865 MHz [173] (disabled)
			* 5885 MHz [177] (disabled)
	Supported commands:
		 * new_interface
		 * set_interface
		 * new_key
		 * start_ap
		 * new_station
		 * set_bss
		 * join_ibss
		 * set_pmksa
		 * del_pmksa
		 * flush_pmksa
		 * remain_on_channel
		 * frame
		 * set_channel
		 * connect
		 * disconnect
	Supported TX frame types:
		 * IBSS: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
		 * managed: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
		 * AP: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
		 * AP/VLAN: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
		 * P2P-client: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
		 * P2P-GO: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
	Supported RX frame types:
		 * IBSS: 0xd0
		 * managed: 0x40 0xd0
		 * AP: 0x00 0x20 0x40 0xa0 0xb0 0xc0 0xd0
		 * AP/VLAN: 0x00 0x20 0x40 0xa0 0xb0 0xc0 0xd0
		 * P2P-client: 0x40 0xd0
		 * P2P-GO: 0x00 0x20 0x40 0xa0 0xb0 0xc0 0xd0
	WoWLAN support:
		 * wake up on anything (device continues operating normally)
	software interface modes (can always be added):
		 * monitor
	interface combinations are not supported
	Device supports scan flush.

**Comment by br101** [comment]
> 10 : 2457 HT40+-
> 11 : 2462 HT40-
> 12 : 2467 HT40-
> 13 : 2472 HT40-
> 14 : 2484 HT20

Your driver reports it can do these channels, but then it does not allow them to be set. This is a driver bug!

As a workaround you can set a upper channel limit, but then it won't scan 5GHz channels...

**Comment by djjerdog** [comment]
Agreed it is a driver bug. To workaround this in HORST could it be set to only scan 2.4 using 20 MHz?

**Comment by br101** [comment]
Yes, see the options in Chan (press c).

**Comment by djjerdog** [comment]
Tried setting the options to 20 MHz under the Channels menu. Get the following errors when selecting either HT20 or 20 (no HT).

Failed to set CH 1 (2412 MHz) HT20 center 2422 after 25804ms                                                                      
Failed to set CH 1 (2412 MHz) 20 (no HT) center 2422 after 30936ms  

Also tried a different adapter that uses a Realtek 8814au chipset and have the same issue with this adapter.

**Comment by br101** [comment]
try setting the channel with "iw" ... if that also doesn't work it's definetly a driver issue.

**Comment by djjerdog** [comment]
Fails using IW as well, tried multiple driver versions, same results :(

wlanpi@wlanpi:~$ sudo iw wlan0 set channel 10 HT40-
wlanpi@wlanpi:~$ sudo iw wlan0 set channel 10 HT40+
command failed: Invalid argument (-22)
wlanpi@wlanpi:~$

**Comment by br101** [comment]
yes, the driver says it can do channel 14 but, when you try to set it, it cant. note that setting HT40+ on channel 10 requires channel 14 to be usable. it's a driver bug and nothing to do with `horst` as I already mentioned above.

**Comment by aallaire01** [comment]
FYI, problem fixed for me after setting regulatory domain.
iw reg set XX

**Comment by djjerdog** [comment]
Thank you, this worked for me!

sudo iw reg set US
