### ISSUE TITLE
Can not get the source IP address

### ISSUE THREAD

**Issue by Esrafilian** [br101/horst#97]
Hello,
I am using horst and I want to log the output data in a file. What is important for me, is the IP address of the source devices but what I get in the file as the IP address is only 0.0.0.0 for all the devices which horst can scan. So, I do appreciate if you could help me to fix this issue.

Best,
Omid

**Comment by br101** [comment]
hi! is the wifi encrypted with WPA or WEP key, maybe?

**Comment by Esrafilian** [comment]
First of all thanks for the reply. Even without any encryption, I get 0.0.0.0. Have you ever tried to get the IP access of the source devices, by any chance?

**Comment by br101** [comment]
yes, this bug did not get noticed recently because of the increasing amount of encrypted networks. i have fixed this now in the master branch
