### ISSUE TITLE
Get bands and channels

### ISSUE THREAD

**Issue by change-my-username** [br101/horst#98]
Hello,
I have a card with MIPS architecture, OpenWrt OS. My problem is that horst detects 1 band and 64 channels, instead of 2 bands, hence, it does not work correctly. For example, I can not enable scan mode, horst always gets error "Channel 1 ? is not available/allowed", it can analyze only one channel.  Here is my output, when I do horst
Got 1 Bands, 64 Channels:
1  : 2412 HT40+
2  : 2417 HT40+
3  : 2422 HT40+
4  : 2427 HT40+
5  : 2432 HT40+-
6  : 2437 HT40+-
7  : 2442 HT40+-
8  : 2447 HT40-
9  : 2452 HT40-
10 : 2457 HT40-
11 : 2462 HT40-
-20: 4900 HT40+
-19: 4905 HT40+
182: 4910 HT40+
183: 4915 HT40+
184: 4920 HT40+-
185: 4925 HT40+-
186: 4930 HT40+-
187: 4935 HT40+-
188: 4940 HT40+-
189: 4945 HT40+-
190: 4950 HT40+-
191: 4955 HT40+-
192: 4960 HT40+-
193: 4965 HT40+-
194: 4970 HT40+-
195: 4975 HT40+-
196: 4980 HT40+-
-3 : 4985 HT40+-
-2 : 4990 HT40+-
-1 : 4995 HT40+-
0  : 5000 HT40+-
1  : 5005 HT40+-
2  : 5010 HT40+-
3  : 5015 HT40+-
4  : 5020 HT40+-
5  : 5025 HT40+-
6  : 5030 HT40+-
7  : 5035 HT40+-
8  : 5040 HT40+-
9  : 5045 HT40+-
10 : 5050 HT40+-
11 : 5055 HT40+-
12 : 5060 HT40+-
13 : 5065 HT40+-
14 : 5070 HT40+-
15 : 5075 HT40+-
16 : 5080 HT40+-
17 : 5085 HT40+-
18 : 5090 HT40+-
19 : 5095 HT40+-
20 : 5100 HT40+-
21 : 5105 HT40+-
22 : 5110 HT40+-
23 : 5115 HT40+-
24 : 5120 HT40+-
25 : 5125 HT40+-
26 : 5130 HT40+-
27 : 5135 HT40+-
28 : 5140 HT40+-
29 : 5145 HT40-
30 : 5150 HT40-
31 : 5155 HT40-
32 : 5160 HT40-
As you can see, the number of some channels is negative. I think, my hardware is ok, because command  "iw phy" displays 2 bands. Could you tell me please all steps of how horst gets bands from "high level" to "low level" or some advice what could it be? And also, I build horst with DEBUG, and debug it and gdb breaks after this line "struct nl_msg *msg = nlmsg_alloc();" at file ifctrl-nl80211.c:93 with warning "GDB can't find the start of the function at 0x77eeaff8." For my card, horst builds with libnl-tiny.

**Comment by aaaaalbert** [comment]
The list shows channels/frequencies from both the 2.4 GHz and 5 GHz bands. It sure looks like *two bands* to me, so the output message is inaccurate.

Re: negative channel numbers, these seem to be a result of an oversight in `libuwifi`'s frequency-to-channel conversion [logic](https://github.com/br101/libuwifi/blob/master/core/wlan_util.c#L397-L400).

The error message you quote is [here in the code](https://github.com/br101/horst/blob/master/network.c#L343), but I'm sorry to say I have no insight about the underlying problem.

What WiFi hardware and OpenWrt / horst versions are you using? (Oh, and does your legislation actually allow the 4.9 GHz channels?)

**Comment by Konstantin-Krinitskiy** [comment]
Wifi driver: ath10k 
horst: horst 5.0 
OpenWrt: DISTRIB_RELEASE='17.01-SNAPSHOT'
My problem is that horst detects 1 bands, but card has 2 ( "iw phy" proved that), hence, It gets error and I can not enable scan mode (I want to see spectrogram)

root@some_name:/etc# iw phy
Wiphy phy0
	max # scan SSIDs: 16
	max scan IEs length: 195 bytes
	max # sched scan SSIDs: 0
	max # match sets: 0
	max # scan plans: 1
	max scan plan interval: -1
	max scan plan iterations: 0
	Retry short limit: 7
	Retry long limit: 4
	Coverage class: 0 (up to 0m)
	Device supports AP-side u-APSD.
	Available Antennas: TX 0x3 RX 0x3
	Configured Antennas: TX 0x3 RX 0x3
	Supported interface modes:
		 * managed
		 * AP
		 * AP/VLAN
		 * monitor
	Band 1:
		Capabilities: 0x19e3
			RX LDPC
			HT20/HT40
			Static SM Power Save
			RX HT20 SGI
			RX HT40 SGI
			TX STBC
			RX STBC 1-stream
			Max AMSDU length: 7935 bytes
			DSSS/CCK HT40
		Maximum RX AMPDU length 65535 bytes (exponent: 0x003)
		Minimum RX AMPDU time spacing: 8 usec (0x06)
		HT TX/RX MCS rate indexes supported: 0-15
		VHT Capabilities (0x338001b2):
			Max MPDU length: 11454
			Supported Channel Width: neither 160 nor 80+80
			RX LDPC
			short GI (80 MHz)
			TX STBC
			RX antenna pattern consistency
			TX antenna pattern consistency
		VHT RX MCS set:
			1 streams: MCS 0-9
			2 streams: MCS 0-9
			3 streams: not supported
			4 streams: not supported
			5 streams: not supported
			6 streams: not supported
			7 streams: not supported
			8 streams: not supported
		VHT RX highest supported: 0 Mbps
		VHT TX MCS set:
			1 streams: MCS 0-9
			2 streams: MCS 0-9
			3 streams: not supported
			4 streams: not supported
			5 streams: not supported
			6 streams: not supported
			7 streams: not supported
			8 streams: not supported
		VHT TX highest supported: 0 Mbps
		Frequencies:
			* 2412 MHz [1] (50.0 dBm)
			* 2417 MHz [2] (50.0 dBm)
			* 2422 MHz [3] (50.0 dBm)
			* 2427 MHz [4] (50.0 dBm)
			* 2432 MHz [5] (50.0 dBm)
			* 2437 MHz [6] (50.0 dBm)
			* 2442 MHz [7] (50.0 dBm)
			* 2447 MHz [8] (50.0 dBm)
			* 2452 MHz [9] (50.0 dBm)
			* 2457 MHz [10] (50.0 dBm)
			* 2462 MHz [11] (50.0 dBm)
			* 2467 MHz [12] (disabled)
			* 2472 MHz [13] (disabled)
			* 2484 MHz [14] (disabled)
	Band 2:
		Capabilities: 0x19e3
			RX LDPC
			HT20/HT40
			Static SM Power Save
			RX HT20 SGI
			RX HT40 SGI
			TX STBC
			RX STBC 1-stream
			Max AMSDU length: 7935 bytes
			DSSS/CCK HT40
		Maximum RX AMPDU length 65535 bytes (exponent: 0x003)
		Minimum RX AMPDU time spacing: 8 usec (0x06)
		HT TX/RX MCS rate indexes supported: 0-15
		VHT Capabilities (0x338001b2):
			Max MPDU length: 11454
			Supported Channel Width: neither 160 nor 80+80
			RX LDPC
			short GI (80 MHz)
			TX STBC
			RX antenna pattern consistency
			TX antenna pattern consistency
		VHT RX MCS set:
			1 streams: MCS 0-9
			2 streams: MCS 0-9
			3 streams: not supported
			4 streams: not supported
			5 streams: not supported
			6 streams: not supported
			7 streams: not supported
			8 streams: not supported
		VHT RX highest supported: 0 Mbps
		VHT TX MCS set:
			1 streams: MCS 0-9
			2 streams: MCS 0-9
			3 streams: not supported
			4 streams: not supported
			5 streams: not supported
			6 streams: not supported
			7 streams: not supported
			8 streams: not supported
		VHT TX highest supported: 0 Mbps
		Frequencies:
			* 4900 MHz [180] (50.0 dBm)
			* 4905 MHz [181] (50.0 dBm)
			* 4910 MHz [182] (50.0 dBm)
			* 4915 MHz [183] (50.0 dBm)
			* 4920 MHz [184] (50.0 dBm)
			* 4925 MHz [185] (50.0 dBm)
			* 4930 MHz [186] (50.0 dBm)
			* 4935 MHz [187] (50.0 dBm)
			* 4940 MHz [188] (50.0 dBm)
			* 4945 MHz [189] (50.0 dBm)
			* 4950 MHz [190] (50.0 dBm)
			* 4955 MHz [191] (50.0 dBm)
			* 4960 MHz [192] (50.0 dBm)
			* 4965 MHz [193] (50.0 dBm)
			* 4970 MHz [194] (50.0 dBm)
			* 4975 MHz [195] (50.0 dBm)
			* 4980 MHz [196] (50.0 dBm)
			* 4985 MHz [197] (50.0 dBm)
			* 4990 MHz [198] (50.0 dBm)
			* 4995 MHz [199] (50.0 dBm)
			* 5000 MHz [200] (50.0 dBm)
			* 5005 MHz [1] (50.0 dBm)
			* 5010 MHz [2] (50.0 dBm)
			* 5015 MHz [3] (50.0 dBm)
			* 5020 MHz [4] (50.0 dBm)
			* 5025 MHz [5] (50.0 dBm)
			* 5030 MHz [6] (50.0 dBm)
			* 5035 MHz [7] (50.0 dBm)
			* 5040 MHz [8] (50.0 dBm)
			* 5045 MHz [9] (50.0 dBm)
			* 5050 MHz [10] (50.0 dBm)
			* 5055 MHz [11] (50.0 dBm)
			* 5060 MHz [12] (50.0 dBm)
			* 5065 MHz [13] (50.0 dBm)
			* 5070 MHz [14] (50.0 dBm)
			* 5075 MHz [15] (50.0 dBm)
			* 5080 MHz [16] (50.0 dBm)
			* 5085 MHz [17] (50.0 dBm)
			* 5090 MHz [18] (50.0 dBm)
			* 5095 MHz [19] (50.0 dBm)
			* 5100 MHz [20] (50.0 dBm)
			* 5105 MHz [21] (50.0 dBm)
			* 5110 MHz [22] (50.0 dBm)
			* 5115 MHz [23] (50.0 dBm)
			* 5120 MHz [24] (50.0 dBm)
			* 5125 MHz [25] (50.0 dBm)
			* 5130 MHz [26] (50.0 dBm)
			* 5135 MHz [27] (50.0 dBm)
			* 5140 MHz [28] (50.0 dBm)
			* 5145 MHz [29] (50.0 dBm)
			* 5150 MHz [30] (50.0 dBm)
			* 5155 MHz [31] (50.0 dBm)
			* 5160 MHz [32] (50.0 dBm)
			* 5165 MHz [33] (50.0 dBm)
			* 5170 MHz [34] (50.0 dBm)
			* 5175 MHz [35] (50.0 dBm)
			* 5180 MHz [36] (50.0 dBm)
			* 5185 MHz [37] (50.0 dBm)
			* 5190 MHz [38] (50.0 dBm)
			* 5195 MHz [39] (50.0 dBm)
			* 5200 MHz [40] (50.0 dBm)
			* 5205 MHz [41] (50.0 dBm)
			* 5210 MHz [42] (50.0 dBm)
			* 5215 MHz [43] (50.0 dBm)
			* 5220 MHz [44] (50.0 dBm)
			* 5225 MHz [45] (50.0 dBm)
			* 5230 MHz [46] (50.0 dBm)
			* 5235 MHz [47] (50.0 dBm)
			* 5240 MHz [48] (50.0 dBm)
			* 5245 MHz [49] (50.0 dBm)
			* 5250 MHz [50] (50.0 dBm)
			* 5255 MHz [51] (50.0 dBm)
			* 5260 MHz [52] (50.0 dBm)
			* 5265 MHz [53] (50.0 dBm)
			* 5270 MHz [54] (50.0 dBm)
			* 5275 MHz [55] (50.0 dBm)
			* 5280 MHz [56] (50.0 dBm)
			* 5285 MHz [57] (50.0 dBm)
			* 5290 MHz [58] (50.0 dBm)
			* 5295 MHz [59] (50.0 dBm)
			* 5300 MHz [60] (50.0 dBm)
			* 5305 MHz [61] (50.0 dBm)
			* 5310 MHz [62] (50.0 dBm)
			* 5315 MHz [63] (50.0 dBm)
			* 5320 MHz [64] (50.0 dBm)
			* 5325 MHz [65] (50.0 dBm)
			* 5330 MHz [66] (50.0 dBm)
			* 5335 MHz [67] (50.0 dBm)
			* 5340 MHz [68] (50.0 dBm)
			* 5345 MHz [69] (50.0 dBm)
			* 5350 MHz [70] (50.0 dBm)
			* 5355 MHz [71] (50.0 dBm)
			* 5360 MHz [72] (50.0 dBm)
			* 5365 MHz [73] (50.0 dBm)
			* 5370 MHz [74] (50.0 dBm)
			* 5375 MHz [75] (50.0 dBm)
			* 5380 MHz [76] (50.0 dBm)
			* 5385 MHz [77] (50.0 dBm)
			* 5390 MHz [78] (50.0 dBm)
			* 5395 MHz [79] (50.0 dBm)
			* 5400 MHz [80] (50.0 dBm)
			* 5405 MHz [81] (50.0 dBm)
			* 5410 MHz [82] (50.0 dBm)
			* 5415 MHz [83] (50.0 dBm)
			* 5420 MHz [84] (50.0 dBm)
			* 5425 MHz [85] (50.0 dBm)
			* 5430 MHz [86] (50.0 dBm)
			* 5435 MHz [87] (50.0 dBm)
			* 5440 MHz [88] (50.0 dBm)
			* 5445 MHz [89] (50.0 dBm)
			* 5450 MHz [90] (50.0 dBm)
			* 5455 MHz [91] (50.0 dBm)
			* 5460 MHz [92] (50.0 dBm)
			* 5465 MHz [93] (50.0 dBm)
			* 5470 MHz [94] (50.0 dBm)
			* 5475 MHz [95] (50.0 dBm)
			* 5480 MHz [96] (50.0 dBm)
			* 5485 MHz [97] (50.0 dBm)
			* 5490 MHz [98] (50.0 dBm)
			* 5495 MHz [99] (50.0 dBm)
			* 5500 MHz [100] (50.0 dBm)
			* 5505 MHz [101] (50.0 dBm)
			* 5510 MHz [102] (50.0 dBm)
			* 5515 MHz [103] (50.0 dBm)
			* 5520 MHz [104] (50.0 dBm)
			* 5525 MHz [105] (50.0 dBm)
			* 5530 MHz [106] (50.0 dBm)
			* 5535 MHz [107] (50.0 dBm)
			* 5540 MHz [108] (50.0 dBm)
			* 5545 MHz [109] (50.0 dBm)
			* 5550 MHz [110] (50.0 dBm)
			* 5555 MHz [111] (50.0 dBm)
			* 5560 MHz [112] (50.0 dBm)
			* 5565 MHz [113] (50.0 dBm)
			* 5570 MHz [114] (50.0 dBm)
			* 5575 MHz [115] (50.0 dBm)
			* 5580 MHz [116] (50.0 dBm)
			* 5585 MHz [117] (50.0 dBm)
			* 5590 MHz [118] (50.0 dBm)
			* 5595 MHz [119] (50.0 dBm)
			* 5600 MHz [120] (50.0 dBm)
			* 5605 MHz [121] (50.0 dBm)
			* 5610 MHz [122] (50.0 dBm)
			* 5615 MHz [123] (50.0 dBm)
			* 5620 MHz [124] (50.0 dBm)
			* 5625 MHz [125] (50.0 dBm)
			* 5630 MHz [126] (50.0 dBm)
			* 5635 MHz [127] (50.0 dBm)
			* 5640 MHz [128] (50.0 dBm)
			* 5645 MHz [129] (50.0 dBm)
			* 5650 MHz [130] (50.0 dBm)
			* 5655 MHz [131] (50.0 dBm)
			* 5660 MHz [132] (50.0 dBm)
			* 5665 MHz [133] (50.0 dBm)
			* 5670 MHz [134] (50.0 dBm)
			* 5675 MHz [135] (50.0 dBm)
			* 5680 MHz [136] (50.0 dBm)
			* 5685 MHz [137] (50.0 dBm)
			* 5690 MHz [138] (50.0 dBm)
			* 5695 MHz [139] (50.0 dBm)
			* 5700 MHz [140] (50.0 dBm)
			* 5705 MHz [141] (50.0 dBm)
			* 5710 MHz [142] (50.0 dBm)
			* 5715 MHz [143] (50.0 dBm)
			* 5720 MHz [144] (50.0 dBm)
			* 5725 MHz [145] (50.0 dBm)
			* 5730 MHz [146] (50.0 dBm)
			* 5735 MHz [147] (50.0 dBm)
			* 5740 MHz [148] (50.0 dBm)
			* 5745 MHz [149] (50.0 dBm)
			* 5750 MHz [150] (50.0 dBm)
			* 5755 MHz [151] (50.0 dBm)
			* 5760 MHz [152] (50.0 dBm)
			* 5765 MHz [153] (50.0 dBm)
			* 5770 MHz [154] (50.0 dBm)
			* 5775 MHz [155] (50.0 dBm)
			* 5780 MHz [156] (50.0 dBm)
			* 5785 MHz [157] (50.0 dBm)
			* 5790 MHz [158] (50.0 dBm)
			* 5795 MHz [159] (50.0 dBm)
			* 5800 MHz [160] (50.0 dBm)
			* 5805 MHz [161] (50.0 dBm)
			* 5810 MHz [162] (50.0 dBm)
			* 5815 MHz [163] (50.0 dBm)
			* 5820 MHz [164] (50.0 dBm)
			* 5825 MHz [165] (50.0 dBm)
			* 5830 MHz [166] (50.0 dBm)
			* 5835 MHz [167] (50.0 dBm)
			* 5840 MHz [168] (50.0 dBm)
			* 5845 MHz [169] (50.0 dBm)
			* 5850 MHz [170] (50.0 dBm)
			* 5855 MHz [171] (50.0 dBm)
			* 5860 MHz [172] (50.0 dBm)
			* 5865 MHz [173] (50.0 dBm)
			* 5870 MHz [174] (50.0 dBm)
			* 5875 MHz [175] (50.0 dBm)
			* 5880 MHz [176] (50.0 dBm)
			* 5885 MHz [177] (50.0 dBm)
			* 5890 MHz [178] (50.0 dBm)
			* 5895 MHz [179] (50.0 dBm)
			* 5900 MHz [201] (50.0 dBm)
			* 5905 MHz [202] (50.0 dBm)
			* 5910 MHz [203] (50.0 dBm)
			* 5915 MHz [204] (50.0 dBm)
			* 5920 MHz [205] (50.0 dBm)
			* 5925 MHz [206] (50.0 dBm)
			* 5930 MHz [207] (50.0 dBm)
			* 5935 MHz [208] (50.0 dBm)
			* 5940 MHz [209] (50.0 dBm)
			* 5945 MHz [210] (50.0 dBm)
			* 5950 MHz [211] (50.0 dBm)
			* 5955 MHz [212] (50.0 dBm)
			* 5960 MHz [213] (50.0 dBm)
			* 5965 MHz [214] (50.0 dBm)
			* 5970 MHz [215] (50.0 dBm)
			* 5975 MHz [216] (50.0 dBm)
			* 5980 MHz [217] (50.0 dBm)
			* 5985 MHz [218] (50.0 dBm)
			* 5990 MHz [219] (50.0 dBm)
			* 5995 MHz [220] (50.0 dBm)
			* 6000 MHz [221] (50.0 dBm)
			* 6005 MHz [222] (50.0 dBm)
			* 6010 MHz [223] (50.0 dBm)
			* 6015 MHz [224] (50.0 dBm)
			* 6020 MHz [225] (50.0 dBm)
			* 6025 MHz [226] (50.0 dBm)
			* 6030 MHz [227] (50.0 dBm)
			* 6035 MHz [228] (50.0 dBm)
			* 6040 MHz [229] (50.0 dBm)
			* 6045 MHz [230] (50.0 dBm)
			* 6050 MHz [231] (50.0 dBm)
			* 6055 MHz [232] (50.0 dBm)
			* 6060 MHz [233] (50.0 dBm)
			* 6065 MHz [234] (50.0 dBm)
			* 6070 MHz [235] (50.0 dBm)
			* 6075 MHz [236] (50.0 dBm)
			* 6080 MHz [237] (50.0 dBm)
			* 6085 MHz [238] (50.0 dBm)
			* 6090 MHz [239] (50.0 dBm)
			* 6095 MHz [240] (50.0 dBm)
			* 6100 MHz [241] (50.0 dBm)
	valid interface combinations:
		 * #{ AP } <= 8,
		   total <= 8, #channels <= 1, STA/AP BI must match
	HT Capability overrides:
		 * MCS: ff ff ff ff ff ff ff ff ff ff
		 * maximum A-MSDU length
		 * supported channel width
		 * short GI for 40 MHz
		 * max A-MPDU length exponent
		 * min MPDU start spacing
	Device supports VHT-IBSS.

**Comment by br101** [comment]
hi! could you please check with current master... there have been many changes to the channel handling there... thanks!
