### ISSUE TITLE
Can't run horst on fedora 28

### ISSUE THREAD

**Issue by morngrar** [br101/horst#99]
This might be the wrong place to address this, but here goes.

I haven't yet tried to build from source. But when installed via the package manager, the file permissions for the binary are such that it cannot open sockets. Once this is fixed, however, it tries to open 'wlan0', which fails because my device is called wlp2s0.

Is there a way to configure horst to use the correct device name? I might try to install it from source later if that's the case.

**Comment by br101** [comment]
run it as root and use -i wlp2s0

**Comment by br101** [comment]
and read at least the output of `horst -h` before asking, please...
